# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-04 06:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_remove_document_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='estado',
            field=models.CharField(default='NA', max_length=16),
        ),
    ]
