# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-04 14:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_docreferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='docreferences',
            name='docChildReferenced',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='el_antiguo_documento', to='documents.Document'),
        ),
        migrations.AlterField(
            model_name='docreferences',
            name='docParentReferencing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='el_nuevo_documento', to='documents.Document'),
        ),
    ]
