# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-04 17:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_auto_20171104_1458'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.Document')),
            ],
        ),
        migrations.CreateModel(
            name='TagModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txtTag', models.CharField(max_length=24)),
            ],
        ),
        migrations.AddField(
            model_name='doctags',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.TagModel'),
        ),
    ]
