# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-05 09:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_auto_20171104_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='docOficialID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='documents.DocumentoOficial'),
        ),
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
