# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-04 07:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Remito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ADMI', 'Administrativo'), ('MESA', 'Mesa de partes')], default='MESA', max_length=4)),
                ('codigo', models.CharField(max_length=32)),
                ('estado', models.CharField(choices=[('ENPROYEC', 'En Proyecto'), ('PARADESP', 'Para Despacho'), ('EMITIDO', 'Emitido'), ('RECIB', 'Recibido'), ('RECIBPAR', 'Recibido Parcial'), ('ATEND', 'Atendido'), ('ATENDPAR', 'Atendido Parcial'), ('ARCH', 'Archivado')], max_length=10)),
                ('codigoDependenciaRemitente', models.CharField(max_length=8)),
                ('dependenciaRemitente', models.CharField(max_length=256)),
                ('codigoEncargadoRemitente', models.CharField(max_length=8)),
                ('encargadoRemitente', models.CharField(max_length=128)),
                ('ruc', models.CharField(max_length=15)),
                ('personaJuridica', models.CharField(max_length=128)),
                ('dni', models.CharField(max_length=8)),
                ('ciudadano', models.CharField(max_length=128)),
                ('otroOrigen', models.CharField(max_length=128)),
                ('codigoOtroOrigen', models.CharField(max_length=128)),
                ('codigoTipoDoc', models.CharField(max_length=5)),
                ('descripcionTipoDoc', models.CharField(max_length=32)),
                ('numeroDoc', models.CharField(max_length=32)),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('asunto', models.CharField(max_length=512)),
            ],
        ),
    ]
