# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-04 12:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remitos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remito',
            name='asunto',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='remito',
            name='ciudadano',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='remito',
            name='codigoDependenciaRemitente',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='remito',
            name='codigoEncargadoRemitente',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='remito',
            name='codigoOtroOrigen',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='remito',
            name='codigoTipoDoc',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='remito',
            name='dependenciaRemitente',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='remito',
            name='descripcionTipoDoc',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='remito',
            name='dni',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='remito',
            name='encargadoRemitente',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='remito',
            name='numeroDoc',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='remito',
            name='otroOrigen',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='remito',
            name='personaJuridica',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='remito',
            name='ruc',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
