# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-05 07:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('remitos', '0002_auto_20171104_1214'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destino',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoDestino', models.CharField(max_length=32)),
                ('tipoDestino', models.CharField(choices=[('DEPEND', 'Dependencia'), ('PERSJU', 'Persona Juridica'), ('CIUDA', 'Ciudadano'), ('OTROOR', 'Otro origen')], default='PERSJU', max_length=8)),
                ('estadoDestino', models.CharField(choices=[('NOLEIDO', 'No leido'), ('RECIBIDO', 'Recibido'), ('ATENDIDO', 'Atendido'), ('ARCHIVADO', 'Archivado')], max_length=10)),
                ('codigoDependenciaDestino', models.CharField(max_length=8, null=True)),
                ('dependenciaDestino', models.CharField(max_length=256, null=True)),
                ('rucDestino', models.CharField(max_length=15, null=True)),
                ('personaJuridicaDestino', models.CharField(max_length=128, null=True)),
                ('dniDestino', models.CharField(max_length=8, null=True)),
                ('ciudadanoDestino', models.CharField(max_length=128, null=True)),
                ('codigoOtroOrigenDestino', models.CharField(max_length=128, null=True)),
                ('otroOrigenDestino', models.CharField(max_length=128, null=True)),
                ('codigoRemito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='remitos.Remito')),
            ],
        ),
        migrations.CreateModel(
            name='Referencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoRef', models.CharField(max_length=32)),
                ('codigoDocRemitoRef', models.CharField(max_length=32)),
                ('codigoDocRemito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='remitos.Remito')),
            ],
        ),
    ]
