# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-04 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='internaluser',
            name='codDependencia',
            field=models.CharField(default='ING', max_length=8),
        ),
    ]
