# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-04 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historiers', '0002_auto_20171104_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='principalstates',
            name='estado',
            field=models.CharField(choices=[('ENPROYEC', 'En Proyecto'), ('PARADESP', 'Para Despacho'), ('EMITIDO', 'Emitido'), ('RECIB', 'Recibido'), ('RECIBPAR', 'Recibido Parcial'), ('ATEND', 'Atendido'), ('ATENDPAR', 'Atendido Parcial'), ('ARCH', 'Archivado')], default='EMITIDO', max_length=2),
        ),
    ]
