# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-04 20:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('historiers', '0003_auto_20171104_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stephistory',
            name='externUserID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.ExternalUser'),
        ),
    ]
