# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-05 07:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegisteredInstitutions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institutionName', models.CharField(max_length=64)),
                ('urlInstitution', models.CharField(max_length=128)),
                ('puerto', models.IntegerField(default=8080)),
            ],
        ),
    ]
